[package]
name = "rbdc-xugu"
version = "4.8.2"
edition = "2021"
repository = "https://github.com/BrightX/rbdc-xugu"
description = "Xugu driver implementation for rbatis. The Rust SQL Toolkit and ORM Library. An async, pure Rust SQL crate featuring compile-time Dynamic SQL"
keywords = ["database", "async", "xugu"]
categories = ["database", "asynchronous"]
authors = [
    "BrightXu <BrightXu666@163.com>",
]
license = "MIT OR Apache-2.0"
include = [
    "src/*",
    "LICENSE*",
    "ReadMe.md",
]

[features]
default = ["lowercase_column_name"]
# 小写列名
lowercase_column_name = []

[dependencies]
rbs = "4"
rbdc = { version = "4.8", default-features = false }

# Futures crates
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc", "sink", "io"] }

# Misc
bitflags = { version = "2", default-features = false, features = ["serde"] }
byteorder = { version = "1.4.3", default-features = false, features = ["std"] }
bytes = "1.1.0"
getrandom = "0.3"
log = "0.4"
num-bigint = { version = "0.4", default-features = false }
turing-cipher = "0.1"
percent-encoding = "2.1.0"
url = "2.2.2"
either = "1.7.0"
fastdate = "0.3"
